### ISSUE TITLE
Support older versions of Python

### ISSUE THREAD

**Issue by inglesp** [inglesp/http-crawler#1]
We currently only test against Python 3.5.

We should be able to support Python 2.7.

**Comment by inglesp** [comment]
To rectify this, we should:
- Add `py27` to the `envlist` in tox.ini.
- Run the tests on Python 2, and what breaks.  At the least, I expect `from urllib.parse import urljoin, urlparse` to fail.
- Fix the code to make the tests pass!  Where possible, I'd like to use [six](https://pythonhosted.org/six/).
- Update .travis.yml to run against Python 2.7.

**Comment by usmanatron** [comment]
Hi @inglesp .  I'm going to have a go at this :-)

**Comment by usmanatron** [comment]
Right, so Ive spent a fair amount of time just trying to get the tests to work and Im failing quite badly...
At the moment its complaining about libxml being missing (though its definitely installed).  It was also not happy about lxml but that seems ok now.

Do you have any tips \ ideas on how I get the tests up and running?
Thanks!

**Comment by inglesp** [comment]
Hi @usmanatron.  Thanks for taking a look at this.

Can you tell me exactly what command you run, and the error message you get?

**Comment by 0xbepresent** [comment]
Hello!.

I'm working in the python 2.7 support and I was seeing your tests and I wonder why you ask for the [assets/somefont.eot and assets/somefont.ttf files](https://github.com/inglesp/http-crawler/blob/master/tests/test_http_crawler.py#L50-L51)?. Those files don't exist in the [assets folder](https://github.com/inglesp/http-crawler/tree/master/tests/site/assets). 

The crawler searchs for URLs that even don't exist?

**Comment by inglesp** [comment]
Hi @misalabs.  The crawler crawls all URLs that are linked to from other pages that it has already crawled.  In this case, `somefont.eot` and `somefont.tff` are linked to from [`styles.css`](https://github.com/inglesp/http-crawler/blob/master/tests/site/assets/styles.css#L19-L20).

Does that answer your question?
