### ISSUE TITLE
Treat URLs with the same root but different fragments as the same

### ISSUE THREAD

**Issue by alexwlchan** [inglesp/http-crawler#9]
Currently http-crawler may attempt to reach the same URL multiple times, if it encounters links with a different fragment. For example, it makes a request for each of the following links:

```
https://next.wellcomecollection.org/articles/animating-the-body
https://next.wellcomecollection.org/articles/animating-the-body#top
https://next.wellcomecollection.org/articles/animating-the-body#shop
https://next.wellcomecollection.org/articles/animating-the-body#caf%C3%A9
https://next.wellcomecollection.org/articles/animating-the-body#restaurant
https://next.wellcomecollection.org/articles/animating-the-body#library
https://next.wellcomecollection.org/articles/animating-the-body#galleries
```

AFAIK, the fragment portion of the URL is only used for page rendering, not routing – so these results either all succeed or all fail (or the page is flakey). URLs with a fragment should only make a request against the fragment-free base URL.

**Comment by inglesp** [comment]
Hi @alexwlchan.  Thanks for the report.  This should be fixed in 0.1.5 which is now on PyPI.
